### ISSUE TITLE
Build issue

### ISSUE THREAD

**Issue by haorenfsa** [milvus-io/bitnami-docker-etcd#7]
### Name and Version

-

### What steps will reproduce the bug?

-

### What is the expected behavior?

https://github.com/milvus-io/bitnami-docker-etcd/pull/6

### What do you see instead?

-

**Comment by jenkoon** [comment]
what is the status

**Comment by jenkoon** [comment]
My env is passed by executing the command "**chmod 777 * -R**"

![image](https://github.com/user-attachments/assets/2fccc6bd-0f7d-4690-8680-d89092234e3f)
